### ISSUE TITLE
Error identification of higher CP2K version

### ISSUE THREAD

**Issue by scott-5** [robinzyb/cp2kdata#10]
Regex in [header_info.py](https://github.com/robinzyb/cp2kdata/blob/main/cp2kdata/block_parser/header_info.py) 
could not identify higher verison info for CP2K version of 7.1/9.1/2022.2.

It will report like that:
```
Traceback (most recent call last):
  File "~/miniconda3/lib/python3.9/site-packages/cp2kdata/output.py", line 84, in __init__
    self.DFTInfo = parse_dft_info(self.filename)
  File "~/miniconda3/lib/python3.9/site-packages/cp2kdata/block_parser/header_info.py", line 81, in parse_dft_info
    return DFTInfo(ks_type=dft_info["ks_type"][0][0][0], multiplicity=dft_info["multiplicity"][0][0][0])
IndexError: list index out of range
```

**Comment by robinzyb** [comment]
Is that possible to provide the outputs? Actually I have write the unittest for 7.1 and 9.1, which should works

**Comment by scott-5** [comment]
[output.log](https://github.com/robinzyb/cp2kdata/files/10072545/output.log)

**Comment by robinzyb** [comment]
> output.log

the output is version 9.1. As you mentioned, 7.1 and 2022.2 are not able to parse as well. Can you provide the outputs with version 7.1 and 2022.2 ?

**Comment by scott-5** [comment]
[output_7.1.log](https://github.com/robinzyb/cp2kdata/files/10086088/output_7.1.log)
[output_2022.2.log](https://github.com/robinzyb/cp2kdata/files/10086090/output_2022.2.log)
Here is it. Please check it.

**Comment by robinzyb** [comment]
The files have print level "low", however, the print level should be medium or higher which contains necessary information.  I have added a commit for checking the print level. see 46598a7db39974747431c5585dc64d9f0787ba37

**Comment by scott-5** [comment]
Thanks.
