### ISSUE TITLE
ask for help when using cp2kdata

### ISSUE THREAD

**Issue by DM0815** [robinzyb/cp2kdata#11]
I meet some questions, when I use cp2kdata, in my file ,there is no force,only energy. but the code cannot load it ,and remind it 'Cp2kOutput' object has no attribute 'energies_list',  in the directoty, there are enter, two xyz files in it.
[output.zip](https://github.com/robinzyb/cp2kdata/files/10138588/output.zip)

**Comment by robinzyb** [comment]
Could you show me how you use the code? The `-frc-1.xyz` file will be necessary for the cp2kdata parser

**Comment by robinzyb** [comment]
I will close this issue in two days if it is no longer active. Please reopen it if the bug can be reproduced
