### ISSUE TITLE
The AIMD data parsed for DeePMD is untrainable 

### ISSUE THREAD

**Issue by DmitryZakiryanov** [robinzyb/cp2kdata#39]
Dear developers, 

I parsed my AIMD data with cp2kdata 0.6.4. and found that DeePMD-kit is struggle to train a model with low RMSEs with these data.
Previously, I used the built-in dpdata functions (kind of old dpdata-native version of parser) to parse this AIMD run and no problems were found: training was succesful. The DeePMD .json training parameters were completely the same. 
Is something wrong with my cp2kdata parsing script? Looks like the data is completely untrainable. In figure, there are RMSE in energies for the cases of native dpdata parser and cp2kdata parser. Forces and virials show large RMSEs as well. I have a weak guess that there could be dimension mismatch (for example, forces are treated as eV/Angstrom instead of Hartree/Bohr or vice versa). 
The CP2K version I used is 6.1. However, I can confirm that for the latest CP2K 2023.2 the problem is remaining.

Sincerely yours, 
Dmitry

The file attached is the log of parsing with cp2kdata
There is the data gained from both dpdata and cp2kdata: https://drive.google.com/file/d/1I9B38WK-17srTUyVa5OtI5wFtIo64exb/view?usp=sharing
There is the archive with raw AIMD data I used: https://drive.google.com/file/d/1Rx6tiBuxLDMuJq8epHW-AKQhFKTNvDHZ/view?usp=sharing

dpdata Python script:
```
import dpdata
import numpy as np

cp2kdata = dpdata.LabeledSystem("1350", fmt="cp2k/aimd_output")
print("# the data contains %d frames" % len(cp2kdata))
index_validation = np.random.choice(len(cp2kdata), size=1500, replace=False)

index_training = list(set(range(len(cp2kdata))) - set(index_validation))
data_training = cp2kdata.sub_system(index_training)
data_validation = cp2kdata.sub_system(index_validation)

data_training.to_deepmd_npy("1350_train")
data_validation.to_deepmd_npy("1350_test")
```

cp2kdata Python script:
```
import dpdata
import numpy as np

cp2kmd_dir = "1350"
cp2kmd_output_name = "LiCl_KCl_1350.log"
cp2kdata = dpdata.LabeledSystem(cp2kmd_dir, cp2k_output_name=cp2kmd_output_name, fmt="cp2kdata/md")
print(cp2kdata)

index_validation = np.random.choice(len(cp2kdata), size=1500, replace=False)
index_training = list(set(range(len(cp2kdata))) - set(index_validation))
data_training = cp2kdata.sub_system(index_training)
data_validation = cp2kdata.sub_system(index_validation)

data_training.to_deepmd_npy("1350_train_cp2kdata")
data_validation.to_deepmd_npy("1350_test_cp2kdata")
```

![egood](https://github.com/robinzyb/cp2kdata/assets/158837121/0f9d4cd0-6c8c-4f83-8198-a7b64485edb5)

[log_cp2kdata.txt](https://github.com/robinzyb/cp2kdata/files/14161058/log_cp2kdata.txt)

**Comment by robinzyb** [comment]
The only difference is in virial. I am checking that. Did you use virial in you dpmd training?

**Comment by DmitryZakiryanov** [comment]
Thank you for the feedback.
Yes, virials were used in training. 
Now we excluded virials and found that RMSEs indeed hugely reduced (by ~10000 times) and model show acceptable errors with testing set. So we can confirm the issue is probably connected with virials. So, this is a bug of parsing?

However, in our experience, inculding virials in error function is necessary. Overvise, the model generally fails to reproduce density with acceptable accuracy. Are you planning to fix virial parsing in future releases? This would be very helpful.

Sincerely yours,
Dmitry

**Comment by robinzyb** [comment]
You're welcome. If you move the `-1.stress` file from the cp2k directory, you can still pase `virial` from cp2k output instead of from `-1.stress` file. The virial from cp2k should be the same as from dpdata. 
For virial in `-1.stress`, you can find it in unit of `bar`, not `GPa` as in cp2k output. However, when I convert to `GPa` by multiply 0.0001, it is not the same value as given in the cp2k output. I am not sure what's wrong here since I don't run npt simulation. 
Do you have any idea? If so, I quick fix this bug in a minute.  For now,  I temporarily disable the parser for `-1.stress`, you can update to cp2k v.0.6.5 from `pip install`

**Comment by robinzyb** [comment]
A recommended setup for now is https://github.com/robinzyb/cp2kdata/blob/main/docs/dpdata_plugin.md 
This can ensure the virial is written in a cp2k output file

**Comment by DmitryZakiryanov** [comment]
Thank you! :) We will try this option

**Comment by robinzyb** [comment]
Hello, does this solve you problem? By the way, have you found the inconsistence bewteen stress in `output` and in `-1.stress` files?

**Comment by robinzyb** [comment]
Thank you. I would keep the code of cp2kdata as now, unless futher investigation or comments on the virial. Actually, I compared the virials from vasp to the virials from cp2k before. There are approximately 1/2 - 1/3 difference. And I don't know the reason.

**Comment by DmitryZakiryanov** [comment]
To date, I can not understand the reason for different virials parsed with cp2kdata and dpdata. The data from (project)-1.stress file (or generated by cp2kdata) obviously correlate with dpdata, although the fit is not perfectly linear. So far I am struggling to interpret such a behavior. In dpdata code, as far as I can tell, virial is stess*volume as well so the reason for such a huge change in virial values written in final .npy files is unclear.

![Figure 2024-03-07 122243](https://github.com/robinzyb/cp2kdata/assets/158837121/d5bd02e1-4866-4846-a2d2-b9384c122326)

**Comment by robinzyb** [comment]
Sorry. I don't understand this.
> To date, I can not understand the reason for different virials parsed with cp2kdata and dpdata.

I prevented  the cp2kdata from read -1.stress file as I said
The virial from cp2kdata and dpdata should be same. both of them are read from stresses in the same output file.
I also multiply them with volume to get virial, and it passed same tests as those in dpdata package. 


The only difference comes from the -1.stress file and the output written by cp2k. I can't convert the values from -1.stress to the values present in the output files for example,  by multiplying 0.0001 to convert from Bar to GPa

**Comment by robinzyb** [comment]
Thanks for the efforts. The old cp2kdata doesn't multiply any factor to covert Bar, which is my miss. I thought stresses in -1.stress are in the unit of GPa while they are not. So you will get much much larger values as you have seen in the figure.

**Comment by remaker789** [comment]
Hello, I think the difference between `output` and `-1.stress`(even  the convertion factor is multiplied) is because the stress in `-1.stress` file also include the contributions from the kinetic energy(i.e. $N k_B T/V$) as discussed in [cp2k google group](https://groups.google.com/g/cp2k/c/QYumahu4sRk). 
Also, As far as I know, the `dpdata` package extracts the stress tensor from `output` file, as you can see from their [source code](https://github.com/deepmodeling/dpdata/blob/18a0ed5ebced8b1f6887038883d46f31ae9990a4/dpdata/cp2k/output.py#L443). Thus, the correct stress tensor should be `&FORCE_EVAL/&PRINT/&STRESS_TENSOR`. However, the `dpdata` package have outdated from the recent cp2k version. 
Alternatively, I think we can output the STRESS_TENSOR to a file, and then read it to get the correct stress tensor, like:
```
&FORCE_EVAL
   &PRINT
        &FORCES ON
        &END FORCES
        &STRESS_TENSOR ON
             COMMON_ITERATION_LEVELS 1000000    ! a very large number to include all your output stress tensor
             FILENAME MYSTRESS
        &END STRESS_TENSOR
   &END PRINT
&END FORCE_EVAL
```
it will create a file named "<PROJECT_NAME>-MYSTRESS.stress_tensor", and the content is like:
![image](https://github.com/robinzyb/cp2kdata/assets/74809885/e172bb49-fdec-4d8b-b6f5-91de2bad37e4)

**Comment by robinzyb** [comment]
>  Alternatively, I think we can output the STRESS_TENSOR to a file, and then read it to get the correct stress tensor, like:

That would be a good idea. Actually, the native dpdata cp2k parser was written by me. However, I found the cp2k output format varies quickly with versions. It is very hard for me to maintaince multiple parser in dpdata. So I create a new package.

**Comment by remaker789** [comment]
Yes, the cp2k output format varies quickly with versions, just a few added spaces will make dpdata not work (o(╥﹏╥)o). Thank you for maintaining cp2kdata.
PS: I found that using FILENAME keyword to output the STRESS_TENSOR to a file will append, not overwrite.

**Comment by robinzyb** [comment]
pity! seems there is no way to control the overwrite ..
