### ISSUE TITLE
cp2k version 9.1

### ISSUE THREAD

**Issue by lizhiqiang100** [robinzyb/cp2kdata#4]
I was recently using dpdata to process cp2k data and found that I was getting results with missing atoms. Finally I found that cp2k version 9.1 is partially incompatible. Can you leave your email and I will send you the output file?

**Comment by robinzyb** [comment]
Hi, I recently refactored the code, and add new plugin for dpdata. you can clone this repository and install. The dpdata plug in will be installed automatically. The format is `fmt=cp2kdata/e_f` for single point energy and `fmt='cp2kdata/md` for md output. For the incompatible version problem, is this problem found in dpdata or cp2kdata(this code.)?
