### ISSUE TITLE
Can Cp2kOutput.get_geo_opt_info_plot output a chosen directory?

### ISSUE THREAD

**Issue by appassionate** [robinzyb/cp2kdata#5]
In following example:
```python
cp2koutput=Cp2kOutput(output_file)
cp2koutput.get_geo_opt_info_plot()
```

A named “geo_opt_info.png” will be output in current directory where might not be well customized.

**Comment by robinzyb** [comment]
please check out the commit. 1ec8f7f6d7f6947ceb0cbedf90d40160d8a73c02
cp2koutput.get_geo_opt_info_plot(dst="somewhere")
