### ISSUE TITLE
Only 1 Frame Detected in AIMD Simulation with CP2K and cp2kdata

### ISSUE THREAD

**Issue by lijiwei2018** [robinzyb/cp2kdata#54]
I am new to CP2K and DeepMD. I have been running AIMD simulations using CP2K and subsequently parsing the data with cp2kdata. However, I encountered an issue where only 1 frame is detected in the output, as shown in the attached screenshot.
![image](https://github.com/robinzyb/cp2kdata/assets/50223360/630aa8bf-8141-4607-b93a-cda8f661c70d)

**Code Snippet**
from cp2kdata import Cp2kOutput
cp2k_output_file = "cp2k.log"
cp2koutput = Cp2kOutput(output_file=cp2k_output_file, run_type="MD")

I have attached a screenshot of the issue for reference. If more information or files are needed, please let me know. Thank you for your assistance!

**Comment by lijiwei2018** [comment]
cp2kdata Version: 0.6.9
Install cp2kdata using pip install cp2kdata.

**Comment by robinzyb** [comment]
Did you install cp2kdata and dpdata in the same python environment?

**Comment by robinzyb** [comment]
please provide the md files so that I can check

**Comment by lijiwei2018** [comment]
@robinzyb 
https://colab.research.google.com/drive/1raCq-81cTf8fYMAc6felA0auWv2rXGtK?usp=drive_link
https://drive.google.com/drive/folders/1vmQDmI_gBSVSqafpCgUeWnHwFrV-t_Jm

**Comment by robinzyb** [comment]
```
cp: cannot stat '/content/drive/MyDrive/202405/cp2k/*': No such file or directory
```

only valid in your google drive.
Also, I found in your screenshot, the run type is parsed as "ENERGY". Did you append different calculations into one output file? If so, please delete the irrelevant content in your output..

**Comment by lijiwei2018** [comment]
Thank you for your help. I modified the Colab notebook, and I will check the output file for any irrelevant content from different calculations and remove it if necessary.

**Comment by robinzyb** [comment]
@lijiwei2018 solved?

**Comment by lijiwei2018** [comment]
@robinzyb My issue has been resolved, thank you.

**Comment by lijiwei2018** [comment]
Hello, I am in the process of creating a dataset to train a force field for Fe3O4 using CPMD simulations. Could you advise on the appropriate size for the unit cell in terms of the number of atoms? Would 56 atoms be sufficient, or should I consider a multiple of 56?

**Comment by robinzyb** [comment]
hi could you move this to discussion of dpgen or deepmd repository??
