### ISSUE TITLE
NotImplementedError: cp2k version=9.1 is not supported yet                     for parsing MD cell from cp2k log files.

### ISSUE THREAD

**Issue by JQ-JQQ** [robinzyb/cp2kdata#56]
I used the log file output from 9.1 and got an error.
 I noticed that the output file in the test is also version 9.1 and NPT_I, but it still got an error. data=dpdata.LabeledSystem("./",cp2k_output_name="output",fmt="cp2kdata/md") 
error: NotImplementedError: cp2k version=9.1 is not supported yet                     for parsing MD cell from cp2k log files.
Could you help me? Thank you very much!

**Comment by robinzyb** [comment]
PS: all md output files in your md folders

**Comment by JQ-JQQ** [comment]
[cp2k-data.tar.gz](https://github.com/user-attachments/files/15865898/cp2k-data.tar.gz)
Thanks for your reply.! Here are all my md files.

**Comment by robinzyb** [comment]
hi, cp2kdata now doesn't support pdb format for pos file output. could you send me md output with pos file of xyz format?
2 or 3 steps of simulation would be best.
the setup instruction:
https://robinzyb.github.io/cp2kdata/docs/dpdata_plugin.html
note that you can also write the `-1.cell` file

**Comment by JQ-JQQ** [comment]
I'm sorry for my oversight, I modified my inp file and it seems to have worked.
Here is the output information:
_--- You are parsing data using package Cp2kData ---
Parsing Energies from ./SbCl-1.ener
Parsing Structures from ./SbCl-pos-1.xyz
Parsing Forces from ./SbCl-frc-1.xyz
Parsing Stresses from ./log
Parsing Cells from ./SbCl-1.cell
Atom names are fake chemical symbols as you set in cp2k input.
Virial Parsing using cp2kdata as plug in for dpdata
was not multiplied by volume before cp2kdata v0.6.4
please check the cp2kdata version and the virial.npy

--- You are parsing data using package Cp2kData ---_

**But what confuses me is that because it is in npy format, I don’t know how to judge the correctness of the extracted data.**  
The submitted files include all md files and npy files.
[cp2k-data-new.tar.gz](https://github.com/user-attachments/files/15963647/cp2k-data-new.tar.gz)

**Comment by JQ-JQQ** [comment]
Thank you very much for your reply！ I will try to look at the output information of the npy file.

**Comment by robinzyb** [comment]
You can now use the newest version of cp2kdata 0.7.0.  https://github.com/robinzyb/cp2kdata/releases/tag/v0.7.0
update the cp2kdata by `pip install cp2kdata -U`

**Comment by JQ-JQQ** [comment]
Thanks for your help, I will try it as soon as possible.
