### ISSUE TITLE
AttributeError: 'Cp2kOutput' object has no attribute 'all_cells'. cp2kdata/e_f couldn't work successfully for my cp2k GEO_OPT files

### ISSUE THREAD

**Issue by TZENjoy** [robinzyb/cp2kdata#74]
Hello, I previously successfully converted a CP2K AIMD task to dpdata/npy format using cp2kdata/md with the help of colleague brother. Recently, I tried to apply a similar conversion for a CP2K GEO_OPT task using `cp2kdata/e_f ` and encountered the error, though the FORCE information added into in the `.inp` file following the manual (https://robinzyb.github.io/cp2kdata/docs/dpdata_plugin.html) . 
Why is this happening? Is `cp2kdata/e_f` indeed suitable for GEO_OPT tasks in CP2K? How should I resolve this issue?  ╯︿╰
the following is the files and bug, and also for `my .inp` file:

```
├── cp2k.out
├── cp2k.sh
├── ini.xyz
├── opt-1.cell
├── opt-1.ener
├── opt-1.restart
├── opt-1.stress
├── opt-BFGS.Hessian
├── opt.cif
├── opt-frc-1.xyz
├── opt.inp
├── opt-pos-1.xyz
├── opt-RESTART.kp
```

```
>>> import dpdata
>>> dpdata.LabeledSystem('cp2k.out', fmt='cp2kdata/e_f').to('deepmd/npy', 'cp2k')
```

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/zengting2/2-software/anaconda3/lib/python3.9/site-packages/dpdata/system.py", line 183, in __init__
self.from_fmt(
File "/home/zengting2/2-software/anaconda3/lib/python3.9/site-packages/dpdata/system.py", line 220, in from_fmt
return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)
File "/home/zengting2/2-software/anaconda3/lib/python3.9/site-packages/dpdata/system.py", line 1113, in from_fmt_obj
data = fmtobj.from_labeled_system(file_name, **kwargs)
File "/home/zengting2/2-software/anaconda3/lib/python3.9/site-packages/cp2kdata/dpdata_plugin.py", line 65, in from_labeled_system
data['cells'] = cp2k_e_f.get_init_cell()[np.newaxis, :, :]
File "/home/zengting2/2-software/anaconda3/lib/python3.9/site-packages/cp2kdata/output.py", line 185, in get_init_cell
return self.all_
cells[0]

AttributeError: 'Cp2kOutput' object has no attribute 'all_cells'
```

[opt.inp.txt](https://github.com/user-attachments/files/16837711/opt.inp.txt)

Best,
Ting

**Comment by robinzyb** [comment]
Hello, I haven't test GEO_OPT for converting to dpdata. so as you can see I have only e_f for single point energy and md for MD outputs. I can update new feature for converting geo_opt data to dpdata if you need, please upload a zip for your geo_opt calculation.

**Comment by TZENjoy** [comment]
Oh, I see! It looks like I misunderstood. It seems that using single-point calculations with cp2kdata/e_f should solve my problem. Thank you so much for your patient response!
