### ISSUE TITLE
Question in converting cp2k v7.1 MD trajectory with cp2kdata v0.6.6-v0.7.1

### ISSUE THREAD

**Issue by Tong-Zhou223** [robinzyb/cp2kdata#77]
When I use cp2kdata to convert cp2k traces to npy format, I get the following error: cp2kdata is running normally, but I don't understand the cause of the problem.
### 
--- You are parsing data using package Cp2kData ---
Parsing Energies   from ./CTF2_water_AIMD-1.ener
Parsing Energies   from ./test.out
Parsing Forces     from ./CTF2_water_AIMD-frc-1.xyz
Parsing Stresses   from ./test.out
Parsing Cells      from ./CTF2_water_AIMD-1.cell
Atom names are fake chemical symbols as you set in cp2k input.
Traceback (most recent call last):
  File "/home/zhout/COFs/sCTF1/AIMD_initial_data/sCTF1_water_10k_testdata/well_train_testdata/single_traject_extract.py", line 5, in <module>
    data=dpdata.LabeledSystem('./',cp2k_output_name='test.out',fmt='cp2k/aimd_output')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhout/software/anaconda3/lib/python3.11/site-packages/dpdata/system.py", line 200, in __init__
    self.from_fmt(
  File "/home/zhout/software/anaconda3/lib/python3.11/site-packages/dpdata/system.py", line 237, in from_fmt
    return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhout/software/anaconda3/lib/python3.11/site-packages/dpdata/system.py", line 1205, in from_fmt_obj
    data = fmtobj.from_labeled_system(file_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhout/software/anaconda3/lib/python3.11/site-packages/cp2kdata/dpdata_plugin.py", line 126, in from_labeled_system
    data['coords'] = cp2kmd.atomic_frames_list
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Cp2kOutput' object has no attribute 'atomic_frames_list'. Did you mean: 'atomic_forces_list'?
###

**Comment by robinzyb** [comment]
hello do you have -pos- file in your output directory?

**Comment by Tong-Zhou223** [comment]
I found that the -pos- of the cp2k trajectory running on another machine can be recognized by cp2kdata, while the -pos- file of the cp2k trajectory running on this machine cannot be recognized, and the trajectorys are all from cp2k-7.1. I would like to find what is the reason for this cp2k-cp2kdata?
Here's the test folder that might be able to give some help.
[cp2kdata_testdata.zip](https://github.com/user-attachments/files/17320442/cp2kdata_testdata.zip)

**Comment by robinzyb** [comment]
Thanks I will check this tomorrow. I got busy these days.

**Comment by Tong-Zhou223** [comment]
> I haven't implemented parser for pos file in .pdb format. Is this format necessary? If so I can implement.

Thank you very much for your reply. I tried again, pbd is not necessary, use xyz format -pos-file will do, thanks again.
