### ISSUE TITLE
cp2k v2024.3

### ISSUE THREAD

**Issue by Cc-12342234** [robinzyb/cp2kdata#78]
Hello Developer,
I’d like to ask if it’s possible to support version 2024.3.

**Comment by robinzyb** [comment]
It throws error? If so, please provide your output file so that I can have a test on it. For MD files, please keep it within 3 steps.

**Comment by Cc-12342234** [comment]
Thank you for your feedback. After trying it out and adding the cell parameter output as prompted, I was able to recognize the output file for version 2024.3. This was an oversight on my part.

But after I added the following parameters, I didn't see a separate output file, and I've set other parameters according to your documentation. Is this enough, or is there no need for any additional operations?
    &STRESS_TENSOR on
        &EACH
	    MD ${frequency}
	&END EACH
    &END STRESS_TENSOR

**Comment by robinzyb** [comment]
Please try to run a samll calculation with several MD steps to test cp2kdata parser. It would save a lot of time!

**Comment by Cc-12342234** [comment]
Thank you for the reminder. I would like to try this approach first to see if I can achieve good training results. I have conducted experiments with smaller results from cp2k 2024.3 (30 steps total) using cp2kdata, and it can be analyzed without any errors. Thanks for your response!

**Comment by robinzyb** [comment]
Glad to see it works. Have a nice day. I will close this issue.
