### ISSUE TITLE
pytest should be just optional dependencies

### ISSUE THREAD

**Issue by njzjz** [robinzyb/cp2kdata#9]
I notice pytest is added to dependencies.

https://github.com/robinzyb/cp2kdata/blob/854d95e9ba29af6691e1327c3cfa8fdedd2981bf/setup.py#L29-L30

Considering it's not used for runtime, it should be just added to optional dependncies.

**Comment by robinzyb** [comment]
thanks for suggestion!

**Comment by robinzyb** [comment]
@njzjz 749d0a176cd014718a8d964578a45c969991c3a8
